project_id = "uvmvyjyqjmqjbxaezkls"

[functions.lei-register]
verify_jwt = false

[functions.lei-lookup]
verify_jwt = false

[functions.lei-renew]
verify_jwt = false

[functions.lei-test-auth]
verify_jwt = false

[functions.lei-test-registration]
verify_jwt = false

[functions.lei-fresh-test]
verify_jwt = false