// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvmvyjyqjmqjbxaezkls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2bXZ5anlxam1xamJ4YWV6a2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjkzODksImV4cCI6MjA3MTk0NTM4OX0.LhXbuuFKyvgAyPvUQU5Awbh9dcLIPL-9Y5rTanC17VI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});